# Generated by Django 5.1.2 on 2024-10-17 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='tickets/', verbose_name='Picture')),
                ('status', models.CharField(choices=[('received', 'Received'), ('investigating', 'Investigating'), ('solved', 'Solved')], default='received', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'support'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to='users.userprofile', verbose_name='Assigned To')),
                ('customer', models.ForeignKey(limit_choices_to={'user_type': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='customer_tickets', to='users.userprofile', verbose_name='Customer')),
            ],
        ),
    ]
